"""python-side defaults

Revision ID: e44cb5174045
Revises: b02bde8a120e
Create Date: 2026-05-07 20:13:14.452664
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e44cb5174045'
down_revision: Union[str, None] = 'b02bde8a120e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
